# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

# Postgres version 9.3.4
#    gem install pg
#    
#    Ensure that pg is defined in your Gemfile
#    gem 'pg'

development:
  adapter: postgresql
  encoding: unicode
  database: ticketee_development
  pool: 5
  host: localhost
  username: Rick
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: ticketee_test
  pool: 5
  host: localhost
  username: Rick
  password: password

